#!/usr/bin/env python3
"""Write qtty/src/width.rs: how many cells of a terminal a character takes.

    tools/gen-width.py > qtty/src/width.rs

A program lays out what it prints by asking its C library how wide each
character is (`wcwidth`), and a terminal that disagrees draws the cursor
somewhere the program does not think it is. So the console uses the same
answer, from the same source: the Unicode character database, by way of the
Python that runs this.

  0  a mark that combines with the character before it, or a character that
     only formats (categories Mn, Me and Cf, and the vowels and finals of
     conjoining Hangul): it takes no cell
  2  East Asian Wide or Fullwidth: it takes two
  1  everything else

Regenerate when the C library's tables move to a new Unicode.
"""
import sys
import unicodedata


def ranges(pred, limit):
    out, start = [], None
    for cp in range(limit):
        if pred(cp):
            if start is None:
                start = cp
        elif start is not None:
            out.append((start, cp - 1))
            start = None
    if start is not None:
        out.append((start, limit - 1))
    return out


def zero(cp):
    if cp == 0x00AD:  # a soft hyphen is drawn where it is shown at all
        return False
    if 0x1160 <= cp <= 0x11FF or cp == 0x200B:
        return True
    return unicodedata.category(chr(cp)) in ("Mn", "Me", "Cf")


def wide(cp):
    return unicodedata.east_asian_width(chr(cp)) in ("W", "F")


LIMIT = 0x20000  # planes 0 and 1; the rest is by rule, below
z = ranges(zero, LIMIT)
w = ranges(wide, LIMIT)


def table(name, rs):
    lines = [f"static {name}: [(u32, u32); {len(rs)}] = ["]
    row = []
    for a, b in rs:
        row.append(f"(0x{a:X}, 0x{b:X})")
        if len(row) == 4:
            lines.append("    " + ", ".join(row) + ",")
            row = []
    if row:
        lines.append("    " + ", ".join(row) + ",")
    lines.append("];")
    return "\n".join(lines)


print(f"""//! How many cells a character takes: 0, 1 or 2.
//!
//! Generated by `tools/gen-width.py` from Unicode {unicodedata.unidata_version}; do not edit.
//!
//! The same question a program asks its C library with `wcwidth`, answered
//! from the same data, because a terminal that disagrees with the program in
//! it about where the cursor is draws the next character in the wrong place.

{table("ZERO", z)}

{table("WIDE", w)}

fn within(table: &[(u32, u32)], cp: u32) -> bool {{
    table
        .binary_search_by(|&(lo, hi)| {{
            if cp < lo {{
                core::cmp::Ordering::Greater
            }} else if cp > hi {{
                core::cmp::Ordering::Less
            }} else {{
                core::cmp::Ordering::Equal
            }}
        }})
        .is_ok()
}}

/// The cells `cp` takes.
pub fn of(cp: u32) -> u8 {{
    if cp < 0x300 {{
        // Latin, and nothing in it combines or is wide but the soft hyphen's
        // neighbours, which the tables below do not have either.
        return 1;
    }}
    if cp >= 0x{LIMIT:X} {{
        // The ideographic planes are wide throughout; the tags and the
        // variation selectors past them take no room.
        return match cp {{
            0x20000..=0x3FFFD => 2,
            0xE0001 | 0xE0020..=0xE007F | 0xE0100..=0xE01EF => 0,
            _ => 1,
        }};
    }}
    if within(&ZERO, cp) {{
        0
    }} else if within(&WIDE, cp) {{
        2
    }} else {{
        1
    }}
}}""")
print(f"{len(z)} zero-width ranges, {len(w)} wide ranges", file=sys.stderr)
